repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        fail_fast: true
        files: ".py$"
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        fail_fast: true
        files: ".py$"
      - id: isort
        name: isort
        entry: isort
        language: system
        fail_fast: true
        files: ".py$"
      - id: pytest
        name: pytest
        entry: pytest tests
        language: system
        fail_fast: true
        always_run: true
        pass_filenames: false
        stages: [push]
