name: Checks

on:
  pull_request:

jobs:
  black:
    runs-on: ubuntu-latest
    name: black Format
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: black Format
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          version: "~= 23.3"
