name: Checks

on:
  pull_request:

jobs:
  black:
    runs-on: ubuntu-latest
    name: black Format
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: black Format
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          version: "~= 23.3"
  pytest:
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: curl -sSL https://install.python-poetry.org | python3 - --version 1.4.0
      - run: poetry install -vv
      - name: Run pytest & coverage
        run: poetry run pytest
